### ISSUE TITLE
Is this the current source for @types/sharepoint

### ISSUE THREAD

**Issue by StefanSchoof** [gandjustas/sptypescript#11]
The text on https://www.npmjs.com/package/@types/sharepoint mentions this project. Is this still the source for @types/sharepoint or is this now https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sharepoint. If this I no longer active a remark with the new URL in the Readme is helpful.

**Comment by gandjustas** [comment]
It's active, but synced with definitelytyped by hands.
I'll change definitelytyped to multiple .d.ts files (like in this repo) in couple weeks.
