### ISSUE TITLE
Incorrect js link names for View, Field, ContentType

### ISSUE THREAD

**Issue by s-KaiNet** [gandjustas/sptypescript#2]
For View, Field, ContentType appropriate property names should be `get_jsLink` and `set_jsLink` (NOT `set_jSLink` and `get_jSLink`)

[SP.View.jsLink](https://msdn.microsoft.com/en-us/library/office/jj246122.aspx)
[SP.Field.jsLink](https://msdn.microsoft.com/en-us/library/office/jj244927.aspx)
[SP.ContentType.jsLink](https://msdn.microsoft.com/en-us/library/office/jj245418.aspx)

**Comment by gandjustas** [comment]
Thanks!
